Prosthetics
GammaStation/Gamma-Station pull request #1
Opened 2018-04-23 10:12 UTC by LudwigVonChesterfield

Добавление возможности выбирать себе производителя протеза куколкам.

<details>
<summary>Описание механоразличий</summary>
На данный момент протезы различаются по таким параметрам:

- Степень защиты от ЭМИ. Некоторые протезы изначально более защищены от ЭМИ воздействия, получая меньше урона от оного.

- Низкокачественность. Некоторые протезы являются "низкокачественными". Это значит, что есть шанс того, что протез будет заспавнен "поломанным". У него будет понижена защита от ЭМИ, а если он отлетит от куклы, он и вовсе может бахнуть.

- Грузоподъёмность, вес, скорость, амортизация. Все влияют на скорость персонажа, но слегка по разному. У груди куклы теперь есть значение "грузоподъёмности", которое определяет насколько тяжёлые, и сколько протезов эта кукла может носить. Можно поставить и больше, но тогда кукла замедлится до скорости дионы. Вес каждого протеза индивидуален, и сумма веса всех протезов сравнивается с грузоподъёмностью. Скорость - базовое ускорение/замедление от каждого протеза этого вида. Амортизация - уменьшение нагрузки при дополнительной нагрузке от одежды. Действует лишь на вес, созданный одеждой(Ригами, бронёй).

- Бёрн и брут резист. Уменьшение получаемого урона от данных видов дамага. Не стакается с резистом расы! Если орган протезирован - резист расы не используется вовсе.

- Протезы с встроенным инструментарием. Некоторые протезы имеют встроенные инструменты, для удобства пользователя.
</details>
<details>
<summary>Превью</summary>

![image](https://user-images.githubusercontent.com/17705613/38563890-a0bc4230-3ce6-11e8-984d-3eceb987fefb.png)

</details>

:cl: Luduk
- rscadd: Протезы для куклы от различных корпораций.
- rscadd: Возможность установки ЭМИ-грида в протез, перед засадкой оного на куклу, для уменьшения степени ЭМИ-воздействия.

2018-05-05 17:10 UTC, Kurshan requested changes
По итогу могу сказать, что мне не нравится состояние баланса. ОСОБЕННО ЭМИ, пускай и с запретом на починку себя любимого.
Совсем хайтир протезы предлагаю делать только в фабрикаторе робототехников, требуя исследования и всё остальное.
И я особо не вчитывался в реальные числа замедления-бафы от протезов, лучше этот момент отдельно проясни. сколько на практике можно будет повысить мувспид?

2018-05-05 17:10 UTC, Kurshan commented on code/game/objects/items/robot/robot_parts.dm
> +	var/has_grid = FALSE              // Used for checking, whether limb has a grid inbuilt.
Давать защиту от ЭМИ - лишать последнего дебаффа на протезы, Чутка ПРОТИВ

2018-05-05 17:10 UTC, Kurshan commented on code/game/objects/items/robot/robot_parts.dm
> +	desc = "[initial(desc)] Model seems to be [model.company]."
у нас для такого есть оператор +=
Правда про оптимизацию строк бьенда я не шибко в курсе. Но не думаю, что будет велика разница.

2018-05-05 17:10 UTC, Kurshan commented on code/game/objects/items/robot/robot_parts.dm
> +	part = BP_HEAD
Зачем два раза переменной присваивать одно и то же значение в объявлении?

2018-05-05 17:10 UTC, Kurshan commented on code/game/objects/items/robot/robot_parts.dm
> +/obj/item/robot_parts/atom_init()
В деструкторе лучше нуллить ссылку model

2018-05-05 17:10 UTC, Kurshan commented on code/game/objects/items/robot/robot_parts.dm
> +	if(istype(W, /obj/item/device/multitool) && hatch_opened)
ELSE

2018-05-05 17:10 UTC, Kurshan commented on code/game/objects/items/robot/robot_parts.dm
> +	if(istype(W, /obj/item/device/radio_grid) && hatch_opened && !has_grid)
Else. Но я всё ещё требую удаления этой фичи

2018-05-05 17:10 UTC, Kurshan commented on code/game/objects/items/stacks/nanopaste.dm
> +				if(H == user) // It must've been done long time ago.
А вот здесь увожение и почёт, я бы предложил развить мысль в подобном ключе.

2018-05-05 17:10 UTC, Kurshan commented on code/game/objects/items/weapons/tools.dm
> +/obj/item/weapon/wrench/prosthetic
Не случится так, что эти инструменты можно будет запихнуть в автолат-протолат-бог_знает_куда ещё? Не уверен, что у нас везде есть проверки на флаг ABSTRACT.

2018-05-05 17:10 UTC, Kurshan commented on code/modules/client/character menu/general.dm
> +							var/limb_name = input(user, "Which limb do you want to change?") as null|anything in list("Head", "Chest", "Groin", "Left Leg","Right Leg","Left Arm","Right Arm")
У нас нет дефайнов для продобных строк?

2018-05-05 17:10 UTC, Kurshan commented on code/modules/client/preferences_savefile.dm
> +	S["organ_prost_data"] 	<< organ_prost_data
Со старыми чарактер-сейвами не будет проблем? Обычно когда затрагиваются как-либо преференсы, мы используем инструменты, чтобы сейв-лоадерные проки обрабатывали старые версии

2018-05-05 17:10 UTC, Kurshan commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/verb/set_prosthetic_tool()
Чутка доебусь, но мы тут в 2018, стоит ли лепить очередные Вербы, когда есть возможность через Гуй?

2018-05-05 17:10 UTC, Kurshan commented on code/modules/mob/living/carbon/human/human.dm
> +	if(arm && (arm.status & ORGAN_ROBOT) && arm.model && arm.model.possible_tools)
Емнип, если конечность и уничтожается, это не значит, что она удаляется из списка, а значит проверка на arm бессмысленна.

2018-05-05 17:10 UTC, Kurshan commented on code/modules/mob/living/carbon/human/human.dm
> +			var/obj/W = get_active_hand()
Ты же в курсе, что get_activa_hand() возвращает объект в руке, а не РУКУ как таковую? А если будет "пустая" рука?

2018-05-05 17:10 UTC, Kurshan commented on code/modules/mob/living/carbon/human/human.dm
> +				put_in_l_hand(tool_created)
Кажется есть Put_in_active_hand

2018-05-05 17:10 UTC, Kurshan commented on code/modules/organs/organ_external.dm
> +	var/sabotaged = FALSE                 // If a prosthetic limb is emagged, it will detonate when it fails.
Если всё это относится к протезу, то почему бы не поместить это в датум model?

2018-05-05 17:10 UTC, Kurshan commented on code/modules/organs/organ_external.dm
> +	var/protected = 0                 // Protection against EMP.
Уже говорил, что против.

2018-05-05 17:10 UTC, Kurshan commented on code/modules/mob/living/carbon/human/human_movement.dm
> +		for(var/obj/item/organ/external/BP in BP_ALL)
Я так понимаю, этот дебафф к скорости меняется не так часто, чтобы высчитывать его каждую секунду(!!!), так что стоит СЕРЬЕЗНО задуматься о том, чтобы хранить значение замедления от протезов в каком-нибудь органе, и пересчитывать его только когда протез добавляется-убирается.

2018-05-05 17:10 UTC, Kurshan commented on code/modules/organs/organ_external.dm
> +						explosion(get_turf(owner), -1, -1, 2, 3)
А сам прок explosion разве самостоятельно не вызывает get_turf?

2018-05-05 17:20 UTC, LudwigVonChesterfield commented on code/game/objects/items/robot/robot_parts.dm
> +	var/has_grid = FALSE              // Used for checking, whether limb has a grid inbuilt.
Это не защита от ЭМИ, а снижение урона от ЭМИ. На одну градацию.

2018-05-05 17:21 UTC, LudwigVonChesterfield commented on code/game/objects/items/robot/robot_parts.dm
> +	part = BP_HEAD
Это из-за ПРа с дионам. Тут его замёржили, а там уже объявлялась переменная. чиним.

2018-05-05 17:21 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_external.dm
> +	var/sabotaged = FALSE                 // If a prosthetic limb is emagged, it will detonate when it fails.
Потому-что датум model общий у всех?

2018-05-12 11:35 UTC, LudwigVonChesterfield commented on code/game/objects/items/robot/robot_parts.dm
> +/obj/item/robot_parts/atom_init()
Уже нуллим.

2018-07-12 08:52 UTC, LudwigVonChesterfield commented
Если не найдётся благий человек с яйцами стали и волей вола, который готов закончить этот ПР. То <s>ЗВе все равно сделает его лучше</s> я наверное закрою его for good

2018-07-13 08:09 UTC, closed without merging