[WiP] Полезная вирусология + Зомби вирус
GammaStation/Gamma-Station pull request #102
Opened 2018-08-05 18:57 UTC by Alexofp

Серьёзный передел механа вирусов и всей вирусологии чтобы сделать её менее грифозной и дать ей наконец полезное применение. Идея в том, чтобы дать возможность вирусологу сделать примерно минут за 20 (допустим до нюки) более-менее полезный вирус.
Симптомы в вирусах больше не должны стоять в определённом порядке, а их количество теперь может варьироваться от 2 до 6. У каждого симптома теперь есть уровнь, чем выше тем симптом считается круче. Сами симптомы были полностью переделаны: очень грифозные удалены, менее грифозные занерфлены и сделаны интересными, остальные сильно углублены и усложнены. Были портированы полезные и не только симтомы с тг стейшена. Ремапить ничего не нужно, машины используются те же, но инкубатор был полностью переделан. Были добавлены две баночки с 10 единицами синаптизина и 5 единицами форона для старта
![default](https://user-images.githubusercontent.com/14040378/43041331-c4b04cc0-8d65-11e8-80f3-62174d4fa1cc.png)
Теперь для изменения вируса требуются химикаты. Облучение бесплатно и просто рандомно перемешивает список симптомов, симптомы всё ещё включаются последовательно, но ещё кстате у каждого симптома так же теперь есть свои стадии. Слип-токсин убирает случайный симтом, вирусная еда добавляет случайный симптом первого уровня, токсин добавляет случайный симптом второго уровня, синаптизин - третьего, форон - четвертого. Используя эти кнопки и происходит изменение вируса. По каждому симптому можно глянуть описание.

<details>
 <summary>Удаленные эффекты (слишком грифонистые или совершенно бесполезные/непонятные)</summary>
Waiting Syndrome<br>
Dead Ear Syndrome (практически копия другого эффекта)<br>
Longevity Syndrome (имба имбанутая которую никто не юзает ибо вики кривая, чинит сломанные кости и лечит по 5 единиц каждого урона)<br>
World Shaking Syndrome<br>
DNA Degradation (просто генетический урон)<br>
Groaning Syndrome<br>
Flemmingtons (что это вообще)
</details>
<br>
<details>
 <summary>Новые эффекты</summary>
Facial Hypertrichosis (2 уровень) - отращивает бороду, включая трапов<br>
Spontaneous Combustion (3 уровень) - рандомно поджигает на пару секунд, довольно забавно<br>
Necrotizing Fasciitis (3 уровень) - дамажит брутом, один из немногих грифонистых симтомов<br>
Autophagocytosis Necrosis (4 уровень) - дамажит брутом поменьше, но почаще<br>
Starlight Condensation (3 уровень) - лечит токсины, брут и бурн урон, если рядом есть *солнечный* свет, тоесть если не далее двух клеток есть тайл с неприкрытым космосом<br>
Toxolysis (4 уровень) - быстрый диализ<br>
Metabolic Boost (4 уровень) - лекарства всасываются в два раза быстрее, голод наступает в три раза быстрее<br>
Nocturnal Regeneration (3 уровень) - лечит брут и бурн урон если стоишь в темноте, ну или сидишь в шкафу, например<br>
Regenerative Coma (4 уровень) - если сумма брут+бурн перепрыгивают за 70, то кукла впадает в кому на 30 секунд, при которой регенерируется по 4 брут и бурн урона в секунду<br>
Mind Restoration (3 уровень) - снимает всякие эффекты, типа головокружения<br>
Sensory Restoration (3 уровень) - лечит глазки и ушки<br>
Quick growth (4 уровень) - при активации сразу включает все симптомы вируса (у каждого симптома всё ещё есть свои стадии, сразу в мартышку не превратишься, например)<br>
Virus booster (3 уровень) - снижает кулдаун всех эффектов вируса в два раза<br>
Structure improvement (3 уровень) - повышает вероятность срабатывания эффектов вируса в два раза<br>
Weight Even (2 уровень) - стабилизирует нутрименты на идеальном уровне, кушать не надо больше
</details>
<br>

<details>
 <summary>Описание старых эффектов (стадии разделены слешем)</summary>
Gibbingtons Syndrome (4 уровень) - сначало пишет простые сообщения, потом делает маленькие взрывы (чисто кнокает, без урона), потом наносится брут урон и может гибнуть конечность, потом гибает полностью<br>
Radian's Syndrome (3 уровень) - безвредное сообщение/немного радиации/больше радиации<br>
Monkism Syndrome (4 уровень) - долгое время пишет сообщения про бананы, потом превращает в мортышку<br>
Suicidal Syndrome (4 уровень) - долгое время пишет рандомные сообщение, от которых хочется суициднуть. Потом может либо нанести 60 оксиурона (вырубаешься секунд на 5) либо очень редко 175 оксиурона (уходишь в крит и медленно умираешь если не помогают)<br>
Toxification Syndrome (3 уровень) - безвредное сообщение/рвота/рандомный токсин в крови из списка<br>
Reverse Pattern Syndrome (4 уровень) - сначало долгие безвредные сообщения. Потом рандомно меняет гены (чисто силы, не внешность)<br>
Shutdown Syndrome (4 уровень) - долгое время сообщения и немного токсинов. Потом наносит либо брут урон либо убивает рандомную конечность (хз что это делает)<br>
Fragile Bones Syndrome (4 уровень) - долгое время безвредные сообщения. Потом может снизить порог урона для перелома для рандомной кости<br>
Hyperacidity (3 уровень) - безвредное сообщение/немного токсинов/больше токсинов<br>
Telepathy Syndrome (3 уровень) - сначало рандомные сообщения. Потом даётся телепатия<br>
Lazy Mind Syndrome (3 уровень) - безвредное сообщение/даёт немного брейн дамага/даёт больше брейд дамага и наносит небольшой урон мозгу<br>
Hallucinational Syndrome (2 уровень) - безвредные сообщения/недолгие галюцинации/долгие галюцинации<br>
Hard of Hearing Syndrome (2 уровень) - безвредные сообщения/глушит на 2 секунды/глушит на 5 секунд либо иногда на 10<br>
Uncontrolled Laughter Effect (2 уровень) - сначало безвредные сообщения. Потом эмоуты улыбки. Потом эмоуты смеха. Потом может застанить и спамить эмоутами смеха на пару секунд<br>
Topographical Cretinism (2 уровень) - безвредные сообщения/гуляешь рандомно 2 секунды/гуляешь рандомно 10 секунд<br>
Loudness Syndrome (2 уровень) - безвредные сообщения/Кукла может сказать рандомные слоги из списка/Кукла может сказать рандомные более громкие фразы из другого списка/кукла кричит<br>
Narcolepsy (1 уровень) - безвредные сообщения/белая пелена на 2 секунды/белая пелена на 5 секунд/белая пелена на 10 секунд и шанс уснуть на 5 секунд<br>
Hyphema (1 уровень) - безвредные сообщения/другая белая пелена на 2 секунды/полностью слепит на 2 секунды/наносит маленький урон глазкам<br>
Appetiser Effect (1 уровень) - заставляет терять нутрименты. На максимальной стадии почти в два раза быстрее голодаешь<br>
Refridgerator Syndrome(1 уровень) - безвредные сообщения/эмоут и немного снижает температуру/сильнее снижает температуру<br>
Hair Loss (1 уровень) - лысеешь через некоторое время<br>
Adrenaline Extra (2 уровень) - безвредные сообщения/генерирует немножко гиперцина/генерирует больше гиперцина<br>
Cough (1 уровень) - безвредные сообщения/эмоут кашля/может заставить уронить маленький предмет из руки либо застанить и спамить эмоутами пару секунд<br>
Sneezing (1 уровень) - безвредные сообщения/эмоут чихания/оставление заразных соплей на полу<br>
Drooling (1 уровень) - безвредные сообщения/эмоут/эмоут чаще<br>
Twitcher (1 уровень) - безвредные сообщения/эмоут/эмоут чаще<br>
Headache (1 уровень) - безвредные сообщения/небольшой голо урон/небольшой голоурон плюс шанс на большой голоурон и стан
</details>

Потестить вроде можно<br>

![default](https://user-images.githubusercontent.com/14040378/43266611-7ec2122e-90f4-11e8-9e65-b89f6813879f.png)
<details>
 <summary>Зомби вирус</summary>
Никак не получить в игре, только через VV. При заражении сначала появляется простой голод, потом слабые признаки какой-то непонятной болезни, потом боль и наконец превращение в зомбика. Зомби не может держать предметы, грабать, дизармить, хелпить и тд, у него всегда в руках "Зомби лапки", которыми он может открывать шлюзы как Алиены и заражать других космонавтиков. Шанс заражения зависит от брони и куда целится зомби. Заражение можно остановить отпилив зараженную конечность (ну если повезло руку/ногу заразить а не грудь там) ну или голову, да. Если зараженные умирают или болезнь доходит до последней стадии, то происходит превращение в зомби примерно через минуту. Зомби можно полностью убить только отпилив голову или гибнув, после обычной смерти они б [...]

2018-08-05 19:01 UTC, AgRevol commented
А проблема того что вирусы становятся слишком НЕ грифонистыми осталась?

2018-08-05 19:07 UTC, Alexofp commented
ну я описал все симптомы и их уровни. Есть два вида рандомных вирусов: слабые и сильные. Слабые состоят только из симптомов не выше 2 уровня, то-есть убить куклу они никак не смогут. Сильные могут состоять из симптомов любого уровня, шанс что попадётся плохой довольно высок. А большинство удаленных грифонистых эффектов я вернул.

2018-08-05 19:09 UTC, AgRevol commented
Просто как первый раз читал возникло ощущение что полезных стало больше чем плохих, но это нужно тестить, хорошо.

2018-08-06 08:29 UTC, Olt1771 commented
Опционально 25 брута с руки у зомби. Десять это не урон

2018-08-06 10:26 UTC, LudwigVonChesterfield commented
Waiting syndrome тащемто интересный довольно «симптом», и вовсе не бесполезный. Позволял бы людей заражаться и заражать вирусом даже не осознавая что они больны, симптомов то нет.

2018-08-06 16:55 UTC, Kurshan requested changes
На сегодня я всё, но я даже не добрался до вирусов, только зомби, си ю сун.

2018-08-06 16:55 UTC, Kurshan commented on code/datums/datumvars.dm
> +					message_admins("\blue [key_name_admin(usr)] infected [key_name(H)] with slow zombie virus.")
Спаны? Здесь и в этом же дифе чуточку ниже.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/admin/admin_verbs.dm
> +				if(D.effects.len < D.max_symptoms)
Я бы объединил эти два ифа.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/admin/admin_verbs.dm
> +				if(D.effects.len > 0)
Здесь тоже

2018-08-06 16:55 UTC, Kurshan commented on code/modules/admin/admin_verbs.dm
> +					for(var/e in (typesof(/datum/disease2/effect) - /datum/disease2/effect))
Каждую итерацию генерить новый лист :( Лучше просто повесить ссылку на временные до while и вместо конструкции `typesof(/datum/disease2/effect) - /datum/disease2/effect)`
Есть subtypesof или как-то так, уже не вспомню, делает тоже самое.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/admin/admin_verbs.dm
> +						holder.chance = rand(holder.effect.chance_minm,holder.effect.chance_maxm)
Пробельчики

2018-08-06 16:55 UTC, Kurshan commented on code/modules/admin/admin_verbs.dm
> +					D.effects-=holder
Да-да, GC порешает, но почему бы не убрать за собой явным удалением? 
UPD. Ещё пробелы забыл.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/inventory.dm
> +			return 0
FALSE

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/life.dm
> +	if(species) species.on_life(src)
На следующую строчку плез

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +/obj/item/weapon/melee/zombie_hand/dropped(mob/user)
Есть же флаг DROPDEL. Зачем тут ещё это?

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +	if(istype(target, /obj))
isobj

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		if(do_after(user,70,target = A))
Пробелы. И обычно после do_after требуется куча проверок по типу не открыта ли уже дверь и так далее. Конкретно в этом случае не подскажу, что именно требуется.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +	if(..() && ishuman(M))
Насколько я помню, результат выполнения прока attack важен, так что лучше использовать конструкцию . = ..()

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +proc/iszombie(mob/living/M)
слэш в начале забыл.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +	if(H.life_tick % 3)
я бы заменил на `if(!H.life_tick % 3) return` и убрал последующий щиттаб

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		if(H.stat != DEAD && prob(20))
Не слишком ли часто? Просто спрашиваю.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		for(var/obj/item/organ/external/organ in H.bodyparts)
Я так понимаю, ношение в руках РУКИ ЗОМБИ обусловлено тем, что требуется запретить зомбарям всё взаимодействие примерно СО ВСЕМ, сделано так себе, но я верю, что иначе пришлось бы перепиливать тонну вещей, ну да ладно, но зачем постоянно морфать руку в лайф проке? У нас же есть on_gain(). И как оно себя ведёт с роботизированными руками? Я прям вижу роботизированные зомби-конености.  В общем хочется услышать мысли на этот счёт.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		H.silent = 5
???

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +proc/handle_infected_death(mob/living/carbon/human/H)
Опять слэш забыл

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +			for(var/mob/dead/observer/ghost in player_list)
Не твоя проблема, но было бы неплохо, если бы кто-то взялся и уже вынес это в отдельный прок здесь и во всех подобных местах с возвращением госта.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +	if(H.organs_by_name[O_BRAIN] && BP && !(BP.status & ORGAN_DESTROYED))
Снова щиттабы

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		//H.rejuvenate()
В чем отличия здесь от режува?

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		for(var/datum/disease2/effectholder/e in V.effects)
Этот фор можно поменять на локейт.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +	infect_virus2(src,D,TRUE)
Пробелы в аргументах

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +	if(species.name == TAJARAN)
Во мне не угасает святая вера в switch.

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/species.dm
> +	H.drop_from_inventory(H.get_active_hand())
drop_l_hand?

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/species.dm
> +		H.l_hand = null
После удаления итема, емнип, ссылка уже подчищается

2018-08-06 16:55 UTC, Kurshan commented on code/modules/mob/living/carbon/species.dm
> +	if(H && istype(H.l_hand, /obj/item/weapon/melee/zombie_hand))
@Сперва обращаемся к полю объекта через ссылку
@Потом два раза проверяем эту пустую ссылку-параметр

2018-08-07 16:18 UTC, Alexofp commented on code/modules/mob/living/carbon/human/zombie.dm
> +		for(var/obj/item/organ/external/organ in H.bodyparts)
Ничего не морфается, только флаг устанавливается. Флаг ORGAN_ZOMBIE нужен только чтобы из рук зомби лапы не выпадали после переломов. А в life я этот флаг переустанавливаю на случай если зомби реджувают и флаг сбрасывается. А протезы выглядят нормально, как протезы

2018-08-07 16:19 UTC, Alexofp commented on code/modules/mob/living/carbon/human/zombie.dm
> +		H.silent = 5
Хотелось запретить зомби болтать без редактирования прока say

2018-08-07 16:20 UTC, Alexofp commented on code/modules/mob/living/carbon/human/zombie.dm
> +		//H.rejuvenate()
Не восстанавливаются отрезанные части тела и переломы

2018-08-07 16:25 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		for(var/obj/item/organ/external/organ in H.bodyparts)
Тогда почему бы не запретить переломы зомбарям?

2018-08-07 16:26 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		//H.rejuvenate()
Добавь лучше какой-нибудь битфлаг, запрещающий реджуквать конкретно части тела, а не эту катастрофическую копипасту

2018-08-07 16:31 UTC, Alexofp commented
Насчёт урона не знаю. 25 урона позволит ломать кости за две тычки, а также ломать укрепленные стекла, нужно ли это? Вся одежда после превращения остаётся на зомби включая броню и шлемы. Но сейчас они получают в 2 раза брута, мне показалось это балансным, не знаю. Топор и лазеры действительно сильны против них, но мне кажется делать их абсолютно не убиваемыми это лишние. Единственный способ убить их сейчас это отпилить или сжечь голову, иначе они встают через минуту. А повалить они могут и сейчас, knocked down может прокнуть

2018-08-07 16:41 UTC, Alexofp commented on code/modules/mob/living/carbon/human/zombie.dm
> +		for(var/obj/item/organ/external/organ in H.bodyparts)
Как? А ещё у куклы переломы могли быть до превращения в зомби

2018-08-07 16:47 UTC, Kurshan commented on code/modules/mob/living/carbon/human/zombie.dm
> +		for(var/obj/item/organ/external/organ in H.bodyparts)
Хиляешь переломы и запрещаешь последующие? Либо игнор переломов в самих конечностях. Не могу прямо сейчас сказать, что будет оптимальнее в этом случае.

2018-08-07 17:22 UTC, Filatelele commented on code/modules/mob/living/carbon/species.dm
> +		H.l_hand = null
Можно же использовать QDEL_NULL(H.l_hand) ?

2018-08-19 13:28 UTC, Moggilazz commented on code/modules/mob/living/carbon/human/life.dm
> +						if(V.spreadtype == "Contact" || V.spreadtype == "Airborne")
А почему воздушно-капельные вирусы передаются при контакте с соплями на полу, когда логичнее оставить только контактные?

2018-08-19 13:28 UTC, Moggilazz commented on code/modules/mob/living/carbon/human/life.dm
> +							infect_virus2(src,V.getcopy())
И здесь тоже

2018-09-18 13:15 UTC, Moggilazz requested changes

2018-09-18 13:15 UTC, Moggilazz commented on code/modules/virus2/effect.dm
> +	proc/activate(mob/living/carbon/mob,datum/disease2/effectholder/holder,datum/disease2/disease/disease)
Надо бы в абсолютные пути переделать

2018-09-18 13:15 UTC, Moggilazz commented on code/modules/virus2/effect.dm
> +	activate(mob/living/carbon/mob,datum/disease2/effectholder/holder,datum/disease2/disease/disease)
Ну собственно и далее по файлу

2018-09-19 13:32 UTC, DieSiege commented
Seems legit.

2018-09-19 13:36 UTC, DieSiege commented
Могиллаз сказал можно мержить - значит мерджим. Seems legit

2018-09-19 13:37 UTC, merged