ВОЗВРАЩЕНИЕ ГОВНА, ИГРА ПО-КРУПНОМУ
GammaStation/Gamma-Station pull request #11
Opened 2018-05-05 07:44 UTC by Moggilazz

Адаптированный под реалии датумов солидщит. Также были исправлены особо жирные баги с датумами с помощью живительных костылей. Правда по-прежнему существует недочёт, когда обляпанными руками трогаешь стены - на них спавнится дефолтная лужи крови со своим названием, но цвет переносится корректно. Также хочу добавить, что не нужно использовать add_dirt_cover напрямую, минуя add_blood - так ломаются некоторые вещи, а оно вам надо?

Итак, возвращаясь к говну:
-Можно срать (эмоут *poo)
-Можно срать в туалет
-Можно срать на закрытый туалет
-Можно сделать дымовую гранату из говна
-Можно кидаться говном
-Бревна и телевизоры срать не могут, потому что это будет говно говна
-Срать никто не заставляет
-Говно

:cl:
 - Вернули говно
 - Починили баги датумов

2018-05-05 15:49 UTC, LudwigVonChesterfield requested changes
Не знаю есть ли у гаммы код стайл, к нему не доёбывался.

2018-05-05 15:49 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/emote.dm
> +			if(species.flags[IS_PLANT] || species.flags[IS_SYNTHETIC])
Эта проверка выведет сообщение о невозможности срать, но все равно позволит срать. Выхода из метода то нет.

2018-05-05 15:49 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Reagents-Poo.dm
> +	restrict_species = list(IPC,DIONA,SHADOWLING,SKELETON,GOLEM)
А почему дерьмо не должно травить дион, и шедоулингов? Или этим товарищам плевать на яды?

2018-05-05 15:49 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Reagents-Poo.dm
> +	if(ishuman(M))
Опять обезьянкам не дали возможности мазаться говном.

2018-05-09 14:22 UTC, WallShrabnic commented on code/modules/reagents/Chemistry-Reagents-Poo.dm
> +	restrict_species = list(IPC,DIONA,SHADOWLING,SKELETON,GOLEM)
Вообще-то да, плевать. Хотя в идеале дионы должны от него хилится

2018-05-31 15:21 UTC, merged