[WIP]Thunderfield
GammaStation/Gamma-Station pull request #118
Opened 2018-08-10 20:24 UTC by Filatelele

Немного WIP, немного говнокод, но это не суть. 

Суть - что-то типо свалки, где игрок может пострелять и устроить дуэли на баллонах. Любителям пострелять больше не нужно дожидаться рольки, чтобы ~~устроить говно~~. 
Работает так - игрок платит 50 кредитов и получает 5 респавнов на тандере. Убийство другого игрока приносит очки, которые можно потратить в отвратительной копипасте аплинка на оружие, броню и всякий другой мусор. 
Автомат можно взломать емагом и получить 10 очков на каждый респавн, нужно быть осторожным - читы вредят здоровью и приводят к брейнроту.

Что сделано на данный момент: 
- [x] VR тела для игроков
- [x] Набросан код игровых подов

TODO list:
- [x] Почистить копипасту и говнокод
- [x] Замаппить игровой зал на станции
- [x] FEATURE - в синий код из подов выбрасывает всех, кроме ассистентов. 
- [x] Сделать карту тандерфилда на Z2 уровне
- [x] Debug?

- [ ] FEATURE - процедурно генерируемая карта тандерфилда(А нужно ли оно?)

<details> 
  <summary>Скриншоты </summary>

![](http://joxi.ru/YmE3qaqs0LknRA.jpg)

</details>

:cl:
 - rscadd[link]:  Battle-royale тандерфилд

2018-08-10 20:29 UTC, Filatelele commented on code/game/objects/items/devices/uplinks.dm
> +/obj/item/device/uplink/hidden/vr_uplink //Uplink for thunderfield
Отвратительная копипаста, простите меня, мейнтейнеры, я не смог придумать ничего лучше

2018-08-10 20:29 UTC, Filatelele commented on code/game/turfs/unsimulated/floor.dm
> +/turf/unsimulated/floor/self_cleaning/proc/cleaner() //Not sure if this is the correct way to do that
Как понятно из комментариев - я не совсем уверен, насколько это легитно делать так

2018-08-10 20:56 UTC, AgRevol commented
А ты запилил рандомные карты для него?

2018-08-10 20:59 UTC, Filatelele commented
Мне это даже в голову не пришло, хех, надо будет запилить

2018-08-27 01:03 UTC, DieSiege commented
Пущай при синем коде важных для станции ребят выплевывает.

2018-08-29 10:07 UTC, Kurshan requested changes
Честно, эту копипасту даже читать уже не хочется, ты бы сперва хоть сам прошёлся по тому, что наделал. Я половину моментов уже подмечать не стал, оставлю это на потом.

2018-08-29 10:07 UTC, Kurshan commented on code/_onclick/hud/other_mobs.dm
> +/datum/hud/proc/vrhuman_hud(ui_style = 'icons/mob/screen_vrhuman.dmi')
Вынеси в отдельный файл вот это вот всё

2018-08-29 10:07 UTC, Kurshan commented on code/game/objects/items/devices/uplinks.dm
> +	world.log << "active?"
Ну ты понял.

2018-08-29 10:07 UTC, Kurshan commented on code/game/turfs/unsimulated/floor.dm
> +	addtimer(CALLBACK(src, .proc/cleaner), CLEANING_DELAY)
Уже Зве намекал, что лучше промышлять таким не на постоянной основе. Я со своей стороны настоятельно рекомендую повесить это на кнопку, которую будут жмякать между раундами егроки. На бее так и сделано, емнип.

2018-08-29 10:07 UTC, Kurshan commented on code/game/turfs/unsimulated/floor.dm
> +			continue
мелочь, но зачем континью, когда можно логическое отрицание сделать?

2018-08-29 10:07 UTC, Kurshan commented on code/modules/thunderfield2562/thunderfield.dm
> +	to_chat(user, "<span class='warning'>You get [points] points! Your total points are: [user.mind.thunder_points]</span>")
При каждом подъеме монеток спамить об этом? Может лучше кнопочку или ещё какой уведомлятор?

2018-08-29 10:07 UTC, Kurshan commented on code/modules/thunderfield2562/thunderfield.dm
> +	if(!points)
Я пока не вижу, где они могут быть проинициализированы

2018-08-29 10:07 UTC, Kurshan commented on code/modules/thunderfield2562/thunderfield_gamepod.dm
> +/obj/machinery/gamepod/attackby(obj/item/I, mob/user)
Копипаста на копипасте. Такое ощущение что даже не смотрел в то, что копируешь-вставляешь

2018-08-29 10:07 UTC, Kurshan commented on code/modules/thunderfield2562/thunderfield_gamepod.dm
> +	T.target_name = "[station_account.owner_name] (via [src.name])"
Нет, серьезно, сделай прок там и вынеси вот эти все действия. Дали вам возможность создания самопальных проков - не хочу, хочу говно жрать

2018-08-29 10:07 UTC, Kurshan commented on code/modules/thunderfield2562/thunderfield_people.dm
> +	see_in_dark = 8 //Just because there is no light on arena
А оно разве не апдейтится в лайф проке?

2018-08-29 10:07 UTC, Kurshan commented on code/modules/thunderfield2562/thunderfield_people.dm
> +	var/obj/randomcatcher/CATCH = new /obj/randomcatcher(src)
Классные названия переменных

2018-08-29 10:07 UTC, Kurshan commented on code/modules/thunderfield2562/thunderfield_people.dm
> +	dog_tag.points = 1
Сперва в инициализации самого объекта выставляем один, потом тут, а потом ещё раз при наличии майнда.

2018-09-13 18:42 UTC, LudwigVonChesterfield commented on code/_onclick/hud/_defines.dm
> +
Невероятно важное изменение касающееся темы билда.

2018-09-13 18:42 UTC, LudwigVonChesterfield commented on code/datums/mind.dm
> +	var/thunder_points = 0 //Points for buying stuff on thunderfield
Даже поменяв тело, небо, аллаха, прожав респавн, кол-во моих очков сохранится. Я не прав?

2018-09-13 18:42 UTC, LudwigVonChesterfield commented on code/datums/uplinks_items.dm
> +		if(!I.item) //That can happen?!
Да, потому-что typesof(/datum/thunderfield_item) включает сам класс /datum/thunderfield_item, у которого это переменная - нулл. Я бы смотрел в сторону subtypesof() ;).

2018-09-13 18:42 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/uplinks.dm
> +/obj/item/device/uplink/hidden/vr_uplink //Uplink for thunderfield
Время идёт, а копипаста. Копипаста не меняется.

2018-09-13 18:42 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/uplinks.dm
> +	world.log << "active?"
15 дней спустя подтверждаю актуальность.

2018-11-23 23:54 UTC, Filatelele commented on code/datums/mind.dm
> +	var/thunder_points = 0 //Points for buying stuff on thunderfield
>Прожав респавн
После прожатия респавна у тебя новый майнд создается, вроде как. Или я не прав? 
>Поменяв тело 
Ну, если у тебя переносят мозг в другое тело - то очки сохраняются, в чем проблема то

2018-11-24 11:15 UTC, Filatelele commented
Короче, это пока-что еще WIP, так как необходимо перелопатить немного копипасты и добавить пару фич.

2018-11-24 21:39 UTC, DieSiege commented
Понеслась душа в рай.

2018-11-24 21:39 UTC, merged