Голографические карты: Эпизод 2 - Новая Надежда
GammaStation/Gamma-Station pull request #12
Opened 2018-05-09 14:08 UTC by Filatelele

Еще более многострадальный порт голографических карт с /VG/

Воксы, нюкеры, обр и дедсад получили свои голографические чипы, которые встраиваются в шлем. Достать их можно с помощью отвертки. Как и раньше - отображают своих тиммейтов на карте. 

<details> 
  <summary>*Клик* </summary>
![](https://user-images.githubusercontent.com/23741266/35742698-5b722ce0-084c-11e8-8ae9-b7f5e1b9ef7e.png)

![](https://user-images.githubusercontent.com/23741266/35742486-a29d83f4-084b-11e8-8ed8-cf578f14fe6f.png)

![](https://user-images.githubusercontent.com/23741266/35742467-98fc30ca-084b-11e8-90f7-aa33bfc66c17.png)

![](https://user-images.githubusercontent.com/23741266/35742457-8fc78194-084b-11e8-917c-419c71b4c9f4.png)
</details>

:cl:
 - rscadd[link]: Добавлены голографические карты.

2018-05-09 15:06 UTC, Kurshan requested changes
Не думаю, что это все моменты, надо будет на более свежую голову мне ещё раз посмотреть. А пока вопрос, чё профайлер говорит про нагрузку всех этих методов?

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/clothing.dm
> +		playsound(user.loc, 'sound/items/Screwdriver.ogg', 100, 1)
Пускай лучше источником будет user. (даже не спрашивай зачем, это давнее извращение и внутренняя надежда)

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/clothing.dm
> +	if(istype(I, /obj/item/weapon/screwdriver))
Else тогда уж

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/clothing.dm
> +	if(istype(I, /obj/item/holochip) && holochip == null)
`holochip == null`
Можно просто знак отрицания поставить жеж

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/clothing.dm
> +	if(istype(I, /obj/item/holochip) && holochip == null)
А так же как по мне, стоит проверку на отсутствие holochip пониже вставить, чтобы юзеру высвечивалась мессага, почему процедура вставки голочипа не прошла

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/clothing.dm
> +		holochip.forceMove(get_turf(src))
Или put_in_hands?

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/spacesuits/alien.dm
> +	.=..()
Пробелов не завезли

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/spacesuits/alien.dm
> +	.=..()
И тут тоже

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/spacesuits/alien.dm
> +	.=..()
И тут

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/spacesuits/ert.dm
> +	.=..()
И даже тут

2018-05-09 15:06 UTC, Kurshan commented on code/modules/clothing/spacesuits/ert.dm
> +	.=..()
Зачем?

2018-05-09 15:06 UTC, Kurshan commented on code/modules/holomaps/holomap_chip.dm
> +	var/role_filter = null
Хоть бы какие комментарии внёс, ну в самом деле же.

2018-05-09 15:06 UTC, Kurshan commented on code/modules/holomaps/holomap_chip.dm
> +	if(!default_holomap)
А как так может получиться, что это же условие может не сработать на 43 строчке?

2018-05-09 15:06 UTC, Kurshan commented on code/modules/holomaps/holomap_lists.dm
> +var/global/list/holochips = list()
Отдельный файл для одной строчки?

2018-05-09 15:06 UTC, Kurshan commented on code/modules/holomaps/holomap_chip.dm
> +//��������������� ���� ��� ������ �����. � ����� ����� ����� ��� ��� ����� ������� ������, �� ���-�� �� �����
ЗИС РАШН ЛЕТТЕРС ИС АНРИДБЛ ВИЗ АУР ТЕКСТ ЕНКОДИНГ

2018-05-09 15:06 UTC, Kurshan commented on code/modules/holomaps/holomap_chip.dm
> +	for(var/i = 1 to ((2 * world.view + 1) * 32))
Кажется был макрос, который относительно быстро собирал лист всех тайлов.

2018-05-09 17:00 UTC, Filatelele commented on code/modules/holomaps/holomap_chip.dm
> +	if(!default_holomap)
Так могло случиться, но я это пофиксил, а потом забыл убрать проверку.

2018-05-10 15:25 UTC, Filatelele commented
Насчет профайлера. Посмотрел, никаких аномальных йоба-нагрузок не обнаружил. Но я себе не очень доверяю, так что лучше, чтобы кто-нибудь еще посмотрел.

2018-05-10 15:31 UTC, Filatelele commented on code/modules/holomaps/holomap_chip.dm
> +	for(var/i = 1 to ((2 * world.view + 1) * 32))
Я нашел только прок spiral_range(), но что-то по его коду я сомневаюсь, что он соберет лист всех тайлов быстрее

2018-05-10 18:35 UTC, Kurshan commented on code/modules/holomaps/holomap_chip.dm
> +	for(var/i = 1 to ((2 * world.view + 1) * 32))
Не то

2018-07-07 11:24 UTC, LudwigVonChesterfield commented on code/modules/holomaps/holomap_chip.dm
> +	for(var/i = 1 to ((2 * world.view + 1) * 32))
RANGE_TURFS

2018-11-24 11:30 UTC, Filatelele commented
Очень глубокий WIP, так как нормальная реализация невозможна без #132 
Stay tuned.

2018-12-10 08:33 UTC, closed without merging