Компактный экстренный охладитель для СПУ.
GammaStation/Gamma-Station pull request #165
Opened 2018-09-03 11:51 UTC by Shudyn

:cl: Shadence
 - rscadd: В стартовую коробку СПУ добавлена не зависимая от скафандра система охлаждения.

2018-09-03 12:36 UTC, Filatelele requested changes
Не вижу прока Destroy()... 
GC, конечно, круто, но все-таки стоит обнулять ссылки на объекты.

2018-09-03 12:36 UTC, Filatelele commented on code/game/objects/items/devices/emergency_cooling.dm
> +	START_PROCESSING(SSobj, src)
Это очень плохой вариант. Объект должен процесситься только тогда, когда он используется. 

Нужно воткнуть START_PROCESSING в прок, где объект активируется, STOP_PROCESSING - в прок, где объект отключается.

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	w_class = 1
Я не то чтобы требую, но есть крутой дефайн.

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	force = 5.0
Все эти волшебные цифры были взяты с фонаря, или скопипащены с родителя?

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	var/on = 0				//is it turned on?
Булевая переменная маскируется под целочисленное.

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	var/cover_open = 0		//is the cover open?
Челочисленная которая на самом деле булевая.

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	var/obj/item/weapon/stock_parts/cell/cell
Ссылка есть, а деструктора нет.

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	cell.loc = src
Используйте forceMove(), дабы уж точно не возникло глупостей.

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	if (!ismob(loc))
Тобишь оно магическим образом охлаждает, только когда не мобе? Звучит интересно, но лучше возможность включать-выключать.

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	H.bodytemperature -= temp_adj*5
Радиатор охлаждает даже людей! Даже деревья! Даже Аллаха!

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	if (ismob(src.loc))
У этих src есть причина?

2018-09-03 12:38 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +			cell.loc = get_turf(loc)
forceMove.

2018-09-03 12:48 UTC, Shudyn commented
Это все есть копипаста с suit_cooling с парой поменяных чисел.
Все вопросы к создателю того кода. Моих познаний пока не хватит для передела "как надо".

2018-09-03 13:07 UTC, Moggilazz commented
Почему нельзя подшаманить уже существующие охладители, чтобы они цеплялись на почти всё и сунуть их генерацию в О2 шкафчики рядом с СК-1

2018-09-03 16:37 UTC, YulianR commented
Ну они нужны двум с половиной спу, им нечего делать в шкафах общих.

2018-09-03 17:39 UTC, Kurshan commented on code/game/objects/items/devices/emergency_cooling.dm
> +	cell.loc = src
ВНЕЗАПНО, но в конструкторе всех обжектов инициализируется расположение объектов.

2018-09-03 17:40 UTC, Kurshan commented on code/game/objects/items/devices/emergency_cooling.dm
> +	cell.use(charge_usage)
use же, емнип, возвращает либо булеан, либо числовое значение, сколько осталось, значит и заряд можно сразу проверить

2018-09-03 17:41 UTC, Kurshan commented on code/game/objects/items/devices/emergency_cooling.dm
> +	if(ishuman(loc))
Щиттабы евривер

2018-09-03 17:55 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	cell.loc = src
А я что-то и не заметил, да

2018-09-03 17:55 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/emergency_cooling.dm
> +	cell = new/obj/item/weapon/stock_parts/cell()	//comes with the crappy default power cell - high-capacity ones shouldn't be hard to find
Локацию можно указывать в конструкторе.

2018-09-04 15:47 UTC, Shudyn commented
Тогда давайте пока закроем этот ПР. Я попробую самостоятельно во всем разобраться. Может еще какие идеи насчет решения этой проблемы придут.

2018-09-04 15:48 UTC, closed without merging