[WIP] Skills
GammaStation/Gamma-Station pull request #319
Opened 2018-10-26 16:06 UTC by TermService

Скиллы не дадут вам делать то, что не положено по профессии, в теории должна решать самую главный спор всея СС. В данном этапе находится в глубокой разработке, хотя основной алгоритм уже готов.

- [ ] Таблица навыков

- [ ] Кодовый расчет скиллпойнтов

- [ ] Введение в механ профессий

- [ ] Дебаг

- [ ] Распределение навыков

:cl: TermService
 - experiment: Добавлена система скиллов

2018-10-26 16:36 UTC, Zap-zapper commented on code/modules/admin/topic.dm
> +			to_chat(usr, "You have not enough powers")
check_rights уже выводит сообщение админу. Этот to_chat здесь не нужен.

2018-10-26 16:47 UTC, Zap-zapper commented on code/modules/client/character menu/skills.dm
> +	. =  "<table cellspacing='0' width='100%'>"
это канеш хорошо что ты знаешь что делает точка, но почему бы не сделать понадёжнее и покрасивее - сделать переменную skill_table, в неё всё записать и её вернуть?

2018-10-26 16:49 UTC, Zap-zapper commented on code/modules/mob/living/carbon/human/human_defense.dm
> +		var/skill_diff = src.getSkill("combat")-user:getSkill("combat")
":" - запрещён. За подробностями к деду

2018-10-26 16:49 UTC, Zap-zapper commented on code/game/machinery/adv_med.dm
> +						fullness = 3
магия

2018-10-26 16:52 UTC, LudwigVonChesterfield requested changes
А ещё мне кажется что круто было бы если бы скилл понижался от боли! Подумай как это можно сделать.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/game/machinery/adv_med.dm
> +						fullness = user:getSkill("medical")
Ммм. А нельзя объявить этот прок абстрактно, и пораньше?

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/game/machinery/adv_med.dm
> +							var/blood_percent =  blood_volume / 560
Внимание, магические цисла.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/game/machinery/adv_med.dm
> +							blood_percent *= 100
Не знаю зачем этому уделять отдельную строку.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/game/machinery/adv_med.dm
> +						fullness = 3
Внимание, магические цифры.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/game/machinery/adv_med.dm
> +					if(fullness>=1)
Забавно что вместо того чтобы "понимать" больше написанного на бумажке, сам состав бумажки будет меняться в зависимости от навыка.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/game/machinery/adv_med.dm
> +					if(issilicon(user))
Инженер борг печатающий профессиональные отчёты о здоровье.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/admin/admin.dm
> +/datum/admins/proc/show_skills(var/mob/living/carbon/human/M as mob in world)
Зачем конструкта as mob, а так же var/?

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/admin/admin.dm
> +	return
Потому-что функция сама себя не завершит? (Он лишний).

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/client/character menu/skills.dm
> +	return
Не знаю как долго я буду докапываться к ретюрнам в конце функции, если они даже не прописаны в кодстайле.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/client/character menu/skills.dm
> +			var/HTML = "<b>[S.name]</b><br>[S.desc]"
Я не сильно хочу лезть в твою копипасту. Но у нас используют вместо макросов спаны.<b> - <span class='bold'>

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/client/character menu/skills.dm
> +			if(!selected) return
if(var1)    else if(var2)    do_this() return

Вкратце, мы стараемся избегать записывания в один ряд условий.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/client/preferences.dm
> +//		addtimer(CALLBACK(src, .proc/mind_skills), 10)
K P A C U B O.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/client/preferences.dm
> +	if(species!="Human")
HUMAN.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/client/preferences.dm
> +		active_age+=4
Это уже настолько часто, что я не здержусь, и скажу. Господи, если тебя попросить, ТермСервис будет ставить пробелы до и после бинарного оператора?

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/client/preferences.dm
> +	if(original_points > 0 && points <= 0) points = 1
Идеальный пример того, чем плоха запись в одну строку.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human_defense.dm
> +		var/skill_diff = src.getSkill("combat")-user:getSkill("combat")
Оператор : не используем, делаем абстрактные методы, или приводим к типу.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/game/machinery/adv_med.dm
> +						fullness = 3
Абстрактный метод getSkill() кстати решил бы эту проблему. Борги выводили бы значение на  всё одинаковым, к примеру.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +var/global/const
Константы маскируются под дефайны. Ещё и записанные относительным путём. Красиво.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +datum/skill/var
Пока-что слэш в начале путя к классу обязателен.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +var/global/list/SKILLS = null
K P A C U B O.

Ещё куча дефайнов маскируются под константы.

Если ты не скажешь зачем сделано именно так(а это как-то связанно со скоростью компиляции), то ты плохой копипастер!

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +proc/setup_skills()
В этом файле всё потеряло свой первый слэш.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +		for(var/T in (typesof(/datum/skill)-/datum/skill))
subtypesof()

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +	if(M.mind.special_role)
var/mod = !!M.mind.special_role выглядело бы смешнее.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +	for(var/V in SKILLS) for(var/datum/skill/S in SKILLS[V])
Цикл в цикле записанные в одну строку. Эти беевцы...

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +				var/list/L = SKILLS[S.field]
Господи какая красота. Похоже дефайны маскировались под константу не просто так.

Для всех страждущих, это ссылка.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +	if(user && user.client && user.client.holder && user.client.holder.rights && R_FUN)
Мы вообще везде проверяем админ ли это.

2018-10-26 16:52 UTC, LudwigVonChesterfield commented on code/modules/mob/skill.dm
> +	switch(points)
У нас вроде уже была идентичная функция.

2018-10-26 16:56 UTC, LudwigVonChesterfield commented
А так как я не мейнтейнер мне вообще плевать что ПР ВИП и на 99% состоит из копипасты! Ахахахахахаххаха!

2018-10-26 16:58 UTC, Kurshan commented on code/modules/client/preferences.dm
> +//		addtimer(CALLBACK(src, .proc/mind_skills), 10)
Не сумел разобраться, вернул спавны 10/10 сходил бы ещё раз в кино
K P A C U B O.

2018-10-26 17:06 UTC, Zap-zapper commented on code/modules/admin/topic.dm
> +		level = min(3,max(0,level))
опять магия. Вообще у тебя дефайны выделены уже, так почему бы их не использовать?

2018-10-26 17:08 UTC, Zap-zapper commented on code/modules/client/character menu/skills.dm
> +			var/selected = input(user, "Select a skillset", "Skillset") as null|anything in SKILL_PRE
короче, эти as null | anything убери

2018-10-26 17:08 UTC, LudwigVonChesterfield commented on code/modules/client/character menu/skills.dm
> +			var/selected = input(user, "Select a skillset", "Skillset") as null|anything in SKILL_PRE
Это же вродь как позволяет ничего не выбрать.

2018-10-26 17:08 UTC, Zap-zapper commented on code/modules/client/preferences.dm
> +//		addtimer(CALLBACK(src, .proc/mind_skills), 10)
ну тут addtimer закомменчен, посему тут спавн это временная мера.

2018-10-30 12:24 UTC, niceping commented
даже интересно че будет. почему-то кажется что это выльется в маринад - когда простые марины даже баночку с таблетками не могли открыть потому что скилла не была

2018-11-11 17:12 UTC, TermService commented on code/modules/admin/topic.dm
> +			to_chat(usr, "You have not enough powers")
fixed

2018-11-11 17:13 UTC, TermService commented on code/modules/client/character menu/skills.dm
> +	. =  "<table cellspacing='0' width='100%'>"
В соседних файлах точки были

2018-11-11 18:35 UTC, TermService commented on code/game/machinery/adv_med.dm
> +							blood_percent *= 100
это было до меня

2018-11-11 18:35 UTC, TermService commented on code/game/machinery/adv_med.dm
> +							var/blood_percent =  blood_volume / 560
Это было до меня

2018-11-29 09:57 UTC, Miracler112 commented on code/modules/mob/skill.dm
> +			var/multiplier = 1
А вот здесь двойной цикл и правда нужен? Обычного `for(var/datum/skill/S in SKILLS` Будет достаточно, а дальше через этот же S делать манипуляции. S.ID же пройдет и двойной цикл нужен не будет

2019-02-12 11:19 UTC, DohrTheMurderer commented
Мейнтейнеры, можете закрывать, тут нихуя не будет

2019-02-12 12:53 UTC, closed without merging