Odysseus sleeper tweak
GammaStation/Gamma-Station pull request #345
Opened 2018-10-28 17:12 UTC by TungstenOctopus

Всех заебали мудаки на одиссеях, которые воруют людей без возможности выбраться. Кароче маленький твик - теперь юзера спрашивает о том, хочет ли он лечь в слипер одиссея.

:cl:
 - tweak: Одиссей не может погрузить игрока в слипер без его согласия

2018-10-28 17:15 UTC, DohrTheMurderer commented
А если кукла без сознания?

2018-10-28 17:17 UTC, TungstenOctopus commented
То же самое, спрашивает ¯\_(ツ)_/¯

2018-10-28 17:22 UTC, Skippeer12 commented
Лучше бы сделал возможность резиста, за основу можно взять тот же код от крио

2018-10-28 17:23 UTC, Armando-Rodriguez17 commented
>Бегаешь за парамеда в Одиссее и пытаешься спасти чью-то куклу
>Пациент без сознания случайно жмёт "нет" или вообще ничего не жмёт, потому что мог после смерти отойти от компа

Либо добавь подбор куклы без сознания все зависимости от желания игрока, либо можешь закрывать ПР.

2018-10-28 17:28 UTC, TungstenOctopus commented
Как прикажете, господин

2018-10-28 17:36 UTC, Skippeer12 commented
Можно ещё таймер больше сделать на погрузку, если цель в сознании.

2018-10-28 20:43 UTC, TungstenOctopus commented
Таки да, повешу ВИП и доделаю

2018-10-28 23:35 UTC, Pivo24 commented
Весело будет доставлять АФК с артериалками

2018-10-29 07:24 UTC, RichardJones1 commented
Thank you, Kanye, VERY COOL

2018-11-05 08:00 UTC, TungstenOctopus commented
Снимаю вип, ибо довел до более или менее нормального состояния

2018-11-05 10:35 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	if(target.stat == UNCONSCIOUS || target.restrained() || !target.canmove)
target.incapacitated() anyone?

2018-11-05 10:35 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		switch(alert(target,"[src] is trying to put you in a sleeper",,"Yes","No"))
Мне нравиться как мехом можно будет станлочить людей, выкидывая им этот алёрт.

2018-11-05 10:35 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		target.client.perspective = EYE_PERSPECTIVE
зачем менять идентацию на закоментированном фрагменте кода.

2018-11-05 10:37 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		if(do_after(user, 300, target = M, can_move = TRUE))
can_move здесь не нужен, и даже мешает.

2018-11-05 10:37 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> -	M.AdjustStunned(-4)
а зачем хилы убирать.

2018-11-05 11:18 UTC, TungstenOctopus commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	if(target.stat == UNCONSCIOUS || target.restrained() || !target.canmove)
Вместо target.stat == UNCONSCIOUS? Или вместо всего?

2018-11-05 11:18 UTC, TungstenOctopus commented on code/game/mecha/equipment/tools/medical_tools.dm
> -	M.AdjustStunned(-4)
Дефолтный слипкр вроде такого не делает, и вообще мне вся эта жопа показалась странной поэтому убрал

2018-11-05 11:19 UTC, TungstenOctopus commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		if(do_after(user, 300, target = M, can_move = TRUE))
А в каких случаях он нужен?

2018-11-05 11:19 UTC, TungstenOctopus commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		switch(alert(target,"[src] is trying to put you in a sleeper",,"Yes","No"))
А как кулдаун прикрутить

2018-11-05 11:20 UTC, TungstenOctopus commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		target.client.perspective = EYE_PERSPECTIVE
Видимо случайно, а так как коммент, не заметил

2018-11-05 14:06 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		if(do_after(user, 300, target = M, can_move = TRUE))
Когда пользователь должен мочь менять локацию. А то выходит ты сначала ему разрешаешь менять локацию, а потом проверяешь не поменял ли он.

2018-11-05 14:07 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		switch(alert(target,"[src] is trying to put you in a sleeper",,"Yes","No"))
Я с мобильного посмотреть не могу, но если бы мы сначала типо подготавливали слипер к погрузке, а потом только спрашивали хочет ли погрузиться игрок - было бы норм. Do_after()

2018-11-05 14:08 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	if(target.stat == UNCONSCIOUS || target.restrained() || !target.canmove)
Ну посмотри Ctrl + F proc/incapacitated, human/incapacitated() что учитывают.

2018-11-11 13:13 UTC, Miracler112 requested changes
Исправь те ошибки, на которые тебе людук указал, что бы ПР дальше пошел

2018-11-11 13:13 UTC, Miracler112 commented on code/game/mecha/equipment/tools/medical_tools.dm
> -	M.AdjustStunned(-4)
Шатать хил не нужно, это стандартный механ слипера всё же. Если конечно у тебя нету альтернативы

2018-11-11 13:16 UTC, StrikS commented
Лучше бы сделали, чтобы жертва поимки была в сознании. И пусть себе орет, что его заперли в Одисее. Раз у вас так уж горит от этого.

2018-11-11 13:30 UTC, TungstenOctopus commented on code/game/mecha/equipment/tools/medical_tools.dm
> -	M.AdjustStunned(-4)
Не представляю зачем там эта ебля со сниманием и накидыванием станов.

2018-11-11 13:38 UTC, Miracler112 commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		if(!chassis.occupant.is_busy() && do_after(chassis.occupant, 20, target = chassis.loc))
Просто интересно, это такая заглушка от спама? Просто ниже после согласия опять идет do_after()

2018-11-11 13:40 UTC, TungstenOctopus commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		if(!chassis.occupant.is_busy() && do_after(chassis.occupant, 20, target = chassis.loc))
Да, именно

2018-11-11 14:19 UTC, Miracler112 commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		if(do_after(user, 300, target = M, can_move = TRUE))
Он его там убрал, тут нормально теперь

2018-11-11 14:28 UTC, Miracler112 approved these changes

2018-11-11 14:41 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> -	M.AdjustStunned(-4)
Не накидывай, только снимай.

2018-11-11 18:27 UTC, TungstenOctopus commented
Короче я хуежник я так вижу, мержите как есть, мне баланс нравится

2018-11-11 18:40 UTC, Miracler112 commented
Хуежник, стан убери внутри слипера и можно будет готовится, а там уже решат, мержить или нет

2018-11-11 18:51 UTC, TungstenOctopus commented
Стана внутри слипера и нет

2018-11-11 18:57 UTC, Miracler112 commented
Действительно, в глаза долблюсь под вечер

2018-11-11 21:12 UTC, merged