tray fix
GammaStation/Gamma-Station pull request #68
Opened 2018-07-21 19:34 UTC by TermService

Поднос работает нормально, теперь если поставить его на стол или на землю продукты на нем появятся рядом с подносом.

2018-07-22 12:20 UTC, Kurshan requested changes
Да, меня не волнует, что АААА это было до меня ОТСТАНЬТЕ, сейчас ты за это взялся, поэтому сделай как полагается.

2018-07-22 12:20 UTC, Kurshan commented on code/game/objects/items/weapons/kitchen.dm
> -	for(M in src.loc) //to handle hand switching
Почему убрал?

2018-07-22 12:20 UTC, Kurshan commented on code/game/objects/items/weapons/kitchen.dm
> +	spawn(1)
Зачем тут спавн?

2018-07-22 12:20 UTC, Kurshan commented on code/game/objects/items/weapons/kitchen.dm
> +		var/foundtable = 0
Эти четыре строчки можно заменить на 
`
var/foundtable = locate(/obj/structure/table) in loc
`

2018-07-22 12:20 UTC, Kurshan commented on code/game/objects/items/weapons/kitchen.dm
> +					for(var/i = 1, i <= rand(1,2), i++)
Фор не по конвеншену, используй синтаксис in to, да и вообще зачем столько сложностей с выкладыванием вещей?

2018-07-23 11:09 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +		var/foundtable = 0
Переменную можно даже не объявлять, ему просто нужно найти стол <code>if(!locate(/obj/structure/table) in loc)</code>

2018-09-30 14:17 UTC, TermService commented on code/game/objects/items/weapons/kitchen.dm
> -	for(M in src.loc) //to handle hand switching
не убрал, оно ниже

2018-09-30 14:17 UTC, TermService commented on code/game/objects/items/weapons/kitchen.dm
> +	spawn(1)
в оригинале написано что обьекты на подносе сходят с ума, поэтому спавн нужен

2018-09-30 14:17 UTC, TermService commented on code/game/objects/items/weapons/kitchen.dm
> +					for(var/i = 1, i <= rand(1,2), i++)
ето было до меня, ето не рефакторинг а фикс

2018-10-03 07:34 UTC, closed without merging