Морг слабы, мешки для трупов из пластика.
GammaStation/Gamma-Station pull request #711
Opened 2019-05-04 11:25 UTC by LudwigVonChesterfield

:cl: Luduk
- rscadd: Крафт мешков для трупов и морг слабов из пластика.

2019-05-05 10:04 UTC, Moggilazz requested changes

2019-05-05 10:04 UTC, Moggilazz commented on code/game/objects/structures/morgue.dm
> +		anchored = !anchored
Нет сообщения и не понятно, произошло что-то или нет

2019-05-05 10:04 UTC, Moggilazz commented on code/game/objects/structures/morgue.dm
> +			new /obj/item/stack/sheet/mineral/plastic(loc, 5, TRUE)
Тупо дропается пластик в бесконечных количествах

2019-05-05 10:05 UTC, Moggilazz commented on code/game/objects/structures/morgue.dm
> +	anchored = FALSE
Актуальных диров всего два, а на выходе получается такая хуйня:
![Gamma Station 2019-05-05 175546](https://user-images.githubusercontent.com/3964933/57192192-55e31600-6f60-11e9-9e04-5a1329b6e4b9.png)

2019-05-05 10:05 UTC, LudwigVonChesterfield commented on code/game/objects/structures/morgue.dm
> +	anchored = FALSE
ах да, их же пуллить можно.

2019-05-05 10:05 UTC, Moggilazz commented on code/game/objects/structures/morgue.dm
> +	else if(istype(P, /obj/item/weapon/crowbar))
Если тыкать открытый морг ломом, можно провернуть такой финт ушами: 
![Gamma Station 2019-05-05 175604](https://user-images.githubusercontent.com/3964933/57192198-698e7c80-6f60-11e9-8f17-b9e3183e8e26.png)

2019-05-05 10:06 UTC, Moggilazz commented on code/game/objects/structures/morgue.dm
> +			new /obj/item/stack/sheet/mineral/plastic(loc, 5, TRUE)
И опять же, моментальная разборка одним кликом

2019-05-10 07:05 UTC, Moggilazz approved these changes

2019-05-10 07:05 UTC, merged